ServerTokens Prod
ServerSignature Off
TraceEnable Off

<Directory /var/www/html/public>
    Options -Indexes
    AllowOverride None
    Require all granted
</Directory>

<FilesMatch "^\.">
    Require all denied
</FilesMatch>
